# Generated by Django 2.2.2 on 2020-03-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='addr',
        ),
    ]
